name: Start SDK Build
on:
  pull_request:
    types: [ opened, edited, reopened, synchronize, ready_for_review ]
    branches: [ main ]

concurrency:
  group: start-pull-request-build-${{ github.ref }}
  cancel-in-progress: true

env:
  REF: ${{ github.ref }}
  IAM_ROLE_ARN: 'arn:aws:iam::332186240596:role/GitHubRole'

jobs:
  aws-sdk-pr-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          role-session-name: PullRequestBuildGitHubAction
          aws-region: us-west-2
      - name: Download Build Script
        run: |
          aws s3 cp s3://aws-sdk-builds-github-assets-alpha-us-west-2/pull-request-build-v1.sh ./.build-scripts/pull-request-build-v1.sh --no-progress
          chmod +x ./.build-scripts/pull-request-build-v1.sh
      - name: Start SDK Build
        run: |
          ./.build-scripts/pull-request-build-v1.sh --gitRef "$REF"
