name: Start SDK Build
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, edited]
    branches: [ main ]

concurrency:
  group: start-pull-request-build-${{ github.ref }}
  cancel-in-progress: true

env:
  IAM_ROLE_ARN: 'arn:aws:iam::332186240596:role/GhircTestRepoGitHubRole'
  DOWNLOAD_FOLDER: '.build-scripts/'
  SCRIPT_LOCATION: 'workflows/start-pull-request-build/pull-request-build-v1.sh'

jobs:
  aws-sdk-pr-build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          role-session-name: PullRequestBuildGitHubAction
          aws-region: us-west-2
      - name: Download Build Script
        run: |
          aws s3 cp s3://aws-sdk-builds-github-assets-alpha-us-west-2/$SCRIPT_LOCATION ./$DOWNLOAD_FOLDER/$SCRIPT_LOCATION --no-progress
          chmod +x ./$DOWNLOAD_FOLDER/$SCRIPT_LOCATION
      - name: Start SDK Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./$DOWNLOAD_FOLDER/$SCRIPT_LOCATION --git-repo "blah!" --git-branch "$GITHUB_HEAD_REF" --git-commit ${{ github.event.pull_request.head.sha }} --git-pr-number ${{ github.event.pull_request.number }}
        timeout-minutes: 510 # 8.5 hours
